#!/usr/bin/env node

const pjson = require('../package')
const program = require('commander')
  .version(pjson.version)
  .usage('<cmd> [options]')
  .command('init', 'initialize project')
  .command('add [modules...]', 'add dependencies')
  .command('install', 'install dependencies')
  .command('build [name]', 'build a cartridge')
  .command('start [options]', 'run the built cartridge (OSX-only)')
  .parse(process.argv)
