#!/usr/bin/env node

const pjson = require('../package')
const program = require('commander')
  .version(pjson.version)
  .usage('<cmd> [options]')
  .command('init', 'initialize project')
  .command('install', 'install dependencies')
  .command('build [name]', 'build a .p8 cartridge')
  .parse(process.argv)
