#!/usr/bin/env node

const pjson = require('../package')
const program = require('commander')
  .version(pjson.version)
  .usage('<cmd> [options]')
  .command('init', 'initialize project')
  .command('install [module]', 'install dependencies')
  .command('build [name]', 'build a .p8 cartridge')
  .command('start [options]', 'run the built .p8 cartridge (OSX-only)')
  .parse(process.argv)
