#!/usr/bin/env node

const program = require('commander')
  .command('p8')
  .usage('add [modules...]')
  .description('add modules as "dependencies" listed in p8.json')
  .parse(process.argv)

const { parse } = require('path')
const { writeSync, prop } = require('./utils')
const filename = `${process.cwd()}/p8.json`
const p8json = require(filename)
const dependencies = program.args
  .map(x => ({ [parse(x).name]: x }))
  .reduce((a = {}, b) => Object.assign({}, a, b), p8json.dependencies)
const json = JSON.stringify(Object.assign({}, p8json, { dependencies }), null, 2)

writeSync(filename, json)
