#!/usr/bin/env node

const program = require('commander')
  .command('p8')
  .usage('add [modules...]')
  .description('add modules as "dependencies" or "gfxDependencies" in p8.json.')
  .option('-s --gfx', 'add as sprite (gfxDependencies)', false)
  .parse(process.argv)

const { args, gfx } = program
const { parse } = require('path')
const { writeSync, prop } = require('./utils')
const filename = `${process.cwd()}/p8.json`
const p8json = require(filename)
const types = {
  '': 'dependencies',
  '.lua': 'dependencies',
  '.moon': 'dependencies',
  '.png': 'gfxDependencies',
  '.jpg': 'gfxDependencies',
  '.gif': 'gfxDependencies'
}
args.forEach(src => {
  const { name, ext } = parse(src)
  let type = types[ext]
  let dep
  if (gfx) type = 'gfxDependencies'
  if (type === 'dependencies') {
    dep = { [name]: src }
  }
  if (type === 'gfxDependencies') {
    dep = { [src]: ext ? ext.substr(1) : 'png' }
  }
  p8json[type] = Object.assign({}, p8json[type], dep)
})
writeSync(filename, JSON.stringify(p8json, null, 2))
