#!/usr/bin/env node

const program = require('commander')
  .command('p8')
  .usage('install')
  .description('install dependencies listed in p8.json to ./pico_modules')
  .parse(process.argv)

const {
  dependencies = {},
  gfxDependencies = {}
} = require(`${process.cwd()}/p8.json`)
const {
  createModulesDir,
  installDependencies,
  installGfxDependencies
} = require('./utils')
createModulesDir()
installDependencies(dependencies)
installGfxDependencies(gfxDependencies)